// backend/routes/categories.js
const express = require("express");
const router = express.Router();
const Category = require("../models/Category");
const Product = require("../models/Product");

// load admin middleware (will throw if missing)
let adminAuth = null;
try {
  adminAuth = require("../middleware/admin");
} catch (e) {
  // fallback — small inline admin middleware if file not present
  adminAuth = (req, res, next) => {
    const adminSecret = process.env.ADMIN_SECRET || "ayo$oya";
    const header = req.headers["x-admin-secret"] || req.query.adminSecret || "";
    if (header !== adminSecret) {
      return res.status(401).json({ error: "Not authorized" });
    }
    next();
  };
}

// GET all categories
router.get("/", async (req, res) => {
  try {
    const cats = await Category.find().sort({ name: 1 });
    res.json(cats);
  } catch (err) {
    console.error("fetch categories error", err);
    res.status(500).json({ error: "Failed to fetch categories" });
  }
});

// GET CATEGORY + PRODUCTS (by slug)
router.get("/:slug/products", async (req, res) => {
  try {
    const slug = req.params.slug;
    const category = await Category.findOne({ slug });
    if (!category) {
      return res.status(404).json({ error: "Category not found" });
    }
    const products = await Product.find({ category: category._id });
    res.json({ category, products });
  } catch (err) {
    console.error("Category product error", err);
    res.status(500).json({ error: "Failed to load category products" });
  }
});

// GET category by ID
router.get("/id/:id", async (req, res) => {
  try {
    const cat = await Category.findById(req.params.id);
    if (!cat) return res.status(404).json({ error: "Category not found" });
    res.json(cat);
  } catch (err) {
    console.error("get category by id error", err);
    res.status(500).json({ error: "Error fetching category" });
  }
});

// ----------------------
// ADMIN: Create category
// POST /api/categories
// body: { name: String, image?: String }
// header: x-admin-secret: <secret>
// ----------------------
router.post("/", adminAuth, async (req, res) => {
  try {
    const { name, image } = req.body;
    if (!name || !name.trim()) return res.status(400).json({ error: "Name is required" });

    // ensure no duplicate slug/name (slug is auto-generated by model)
    const existing = await Category.findOne({ name: new RegExp(`^${name.trim()}$`, "i") });
    if (existing) return res.status(400).json({ error: "Category already exists" });

    const cat = await Category.create({ name: name.trim(), image: image || "" });
    res.status(201).json(cat);
  } catch (err) {
    console.error("create category error", err);
    res.status(500).json({ error: "Failed to create category" });
  }
});

// ----------------------
// ADMIN: Update category
// PUT /api/categories/:id
// body: { name?: String, image?: String }
// header: x-admin-secret
// ----------------------
router.put("/:id", adminAuth, async (req, res) => {
  try {
    const updates = {};
    if (typeof req.body.name === "string") updates.name = req.body.name.trim();
    if (typeof req.body.image === "string") updates.image = req.body.image;

    const cat = await Category.findByIdAndUpdate(req.params.id, updates, { new: true, runValidators: true });
    if (!cat) return res.status(404).json({ error: "Category not found" });
    res.json(cat);
  } catch (err) {
    console.error("update category error", err);
    res.status(500).json({ error: "Failed to update category" });
  }
});

// ----------------------
// ADMIN: Delete category
// DELETE /api/categories/:id
// header: x-admin-secret
// ----------------------
router.delete("/:id", adminAuth, async (req, res) => {
  try {
    const cat = await Category.findById(req.params.id);
    if (!cat) return res.status(404).json({ error: "Category not found" });

    // optional: ensure no products exist in the category
    const productCount = await Product.countDocuments({ category: cat._id });
    if (productCount > 0) {
      return res.status(400).json({ error: "Cannot delete category with products" });
    }

    await Category.findByIdAndDelete(req.params.id);
    res.json({ ok: true, message: "Category deleted" });
  } catch (err) {
    console.error("delete category error", err);
    res.status(500).json({ error: "Failed to delete category" });
  }
});

module.exports = router;
